# Generated by Django 4.2.1 on 2023-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0002_delete_administrator_delete_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
